### ISSUE TITLE
Could not work properly

### ISSUE THREAD

**Issue by starjason** [bobrik/mesos-compose#12]
master and slave is  Exited.

docker ps -a
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS                       PORTS               NAMES
40511515f807        mesosphere/mesos-slave:0.28.1-2.0.20.ubuntu1404    "mesos-slave"            9 minutes ago       Exited (134) 9 minutes ago                       mesoscompose_slave-one_1
3b280f186549        mesosphere/mesos-master:0.28.1-2.0.20.ubuntu1404   "mesos-master --regis"   9 minutes ago       Exited (139) 9 minutes ago                       mesoscompose_master_1
5f0db5bd3ec1        mesosphere/marathon:v1.1.1                         "./bin/start"            9 minutes ago       Up 9 minutes                                     mesoscompose_marathon_1
af71dc447fde        bobrik/zookeeper                                   "/run.sh"                9 minutes ago       Up 9 minutes                                     mesoscompose_zk_1

**Comment by bobrik** [comment]
How do you run it?

**Comment by starjason** [comment]
git clone https://github.com/bobrik/mesos-compose
cd mesos-compose
docker-compose up -d

**Comment by bobrik** [comment]
Please read the README, it describes what you need to know.
