### ISSUE TITLE
Doesn't support Docker for Mac

### ISSUE THREAD

**Issue by mre** [bobrik/mesos-compose#13]
Hi,

thanks for your project.
I just tried running it on my Macbook using Docker for Mac.

When I execute `make run` the containers exit.
Here's the output:

```
slave-one_1  | Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127
```

I think the reason is that the docker binary mounted into the container is a Mac binary, while it actually runs in a Linux Virtual Machine:

```
❯❯❯ file /usr/local/bin/docker
/usr/local/bin/docker: Mach-O 64-bit executable x86_64
```

**Comment by bobrik** [comment]
It is mentioned in the readme: https://github.com/bobrik/mesos-compose#compatibility

**Comment by bobrik** [comment]
There's nothing I can do to make it work. In fact, I had to revert back to docker machine myself.

**Comment by mre** [comment]
Whoops. I see. Sorry for the noise.
